version: '3.3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_dev
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: gunicorn pokeapi.wsgi:application --bind 0.0.0.0:8000
    restart: always    
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
